#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : onig
Version  : 6.9.8
Release  : 28
URL      : https://github.com/kkos/oniguruma/releases/download/v6.9.8/onig-6.9.8.tar.gz
Source0  : https://github.com/kkos/oniguruma/releases/download/v6.9.8/onig-6.9.8.tar.gz
Summary  : Regular expression library
Group    : Development/Tools
License  : BSD-3-Clause
Requires: onig-bin = %{version}-%{release}
Requires: onig-lib = %{version}-%{release}
Requires: onig-license = %{version}-%{release}

%description
Oniguruma  ----   (C) K.Kosako
https://github.com/kkos/oniguruma
FIXED Security Issues (in Oniguruma 6.3.0):
CVE-2017-9224, CVE-2017-9225, CVE-2017-9226
CVE-2017-9227, CVE-2017-9228, CVE-2017-9229

%package bin
Summary: bin components for the onig package.
Group: Binaries
Requires: onig-license = %{version}-%{release}

%description bin
bin components for the onig package.


%package dev
Summary: dev components for the onig package.
Group: Development
Requires: onig-lib = %{version}-%{release}
Requires: onig-bin = %{version}-%{release}
Provides: onig-devel = %{version}-%{release}
Requires: onig = %{version}-%{release}

%description dev
dev components for the onig package.


%package lib
Summary: lib components for the onig package.
Group: Libraries
Requires: onig-license = %{version}-%{release}

%description lib
lib components for the onig package.


%package license
Summary: license components for the onig package.
Group: Default

%description license
license components for the onig package.


%prep
%setup -q -n onig-6.9.8
cd %{_builddir}/onig-6.9.8

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1666028350
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -Ofast -falign-functions=32 -ffat-lto-objects -flto=auto -fno-semantic-interposition -mprefer-vector-width=256 "
export FCFLAGS="$FFLAGS -O3 -Ofast -falign-functions=32 -ffat-lto-objects -flto=auto -fno-semantic-interposition -mprefer-vector-width=256 "
export FFLAGS="$FFLAGS -O3 -Ofast -falign-functions=32 -ffat-lto-objects -flto=auto -fno-semantic-interposition -mprefer-vector-width=256 "
export CXXFLAGS="$CXXFLAGS -O3 -Ofast -falign-functions=32 -ffat-lto-objects -flto=auto -fno-semantic-interposition -mprefer-vector-width=256 "
%configure --disable-static --enable-binary-compatible-posix-api=yes
make  %{?_smp_mflags}

%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make %{?_smp_mflags} check

%install
export SOURCE_DATE_EPOCH=1666028350
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/onig
cp %{_builddir}/onig-%{version}/COPYING %{buildroot}/usr/share/package-licenses/onig/061a5f18d5b7a5fe6a1da9419bef05b7d35f7cf6 || :
%make_install

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/onig-config

%files dev
%defattr(-,root,root,-)
/usr/include/oniggnu.h
/usr/include/onigposix.h
/usr/include/oniguruma.h
/usr/lib64/libonig.so
/usr/lib64/pkgconfig/oniguruma.pc

%files lib
%defattr(-,root,root,-)
/usr/lib64/libonig.so.5
/usr/lib64/libonig.so.5.3.0

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/onig/061a5f18d5b7a5fe6a1da9419bef05b7d35f7cf6
