#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : onig
Version  : 6.5.0
Release  : 11
URL      : https://github.com/kkos/oniguruma/releases/download/v6.5.0/onig-6.5.0.tar.gz
Source0  : https://github.com/kkos/oniguruma/releases/download/v6.5.0/onig-6.5.0.tar.gz
Summary  : Regular expression library
Group    : Development/Tools
License  : BSD-2-Clause
Requires: onig-bin
Requires: onig-lib

%description
Oniguruma  ----   (C) K.Kosako <kkosako0@gmail.com>
https://github.com/kkos/oniguruma

%package bin
Summary: bin components for the onig package.
Group: Binaries

%description bin
bin components for the onig package.


%package dev
Summary: dev components for the onig package.
Group: Development
Requires: onig-lib
Requires: onig-bin
Provides: onig-devel

%description dev
dev components for the onig package.


%package lib
Summary: lib components for the onig package.
Group: Libraries

%description lib
lib components for the onig package.


%prep
%setup -q -n onig-6.5.0

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1501750719
%configure --disable-static
make V=1  %{?_smp_mflags}

%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make VERBOSE=1 V=1 %{?_smp_mflags} check

%install
export SOURCE_DATE_EPOCH=1501750719
rm -rf %{buildroot}
%make_install

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/onig-config

%files dev
%defattr(-,root,root,-)
/usr/include/*.h
/usr/lib64/libonig.so
/usr/lib64/pkgconfig/oniguruma.pc

%files lib
%defattr(-,root,root,-)
/usr/lib64/libonig.so.4
/usr/lib64/libonig.so.4.0.0
